# Generated by Django 5.2.5 on 2025-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
