# Generated by Django 5.2.5 on 2025-10-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='created_at',
        ),
    ]
