# Generated by Django 5.2.5 on 2025-10-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_hospital_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
