# Generated by Django 5.2.5 on 2025-10-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_appointment_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accounts.hospital')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccine Inventory',
                'verbose_name_plural': 'Vaccine Inventories',
                'unique_together': {('hospital', 'vaccine')},
            },
        ),
    ]
